services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
  db:
    image: postgres:17.4
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file: .env
